import { DayStatus, CheckInStatus, CheckOutStatus } from '@softtime/shared';
import type { Attendance } from '@softtime/shared';

export const mockTodayAttendance: Attendance = {
  id: 'att-today-001',
  companyId: 'company-001',
  userId: 'user-worker-001',
  date: new Date('2026-06-07'),
  checkInAt: new Date('2026-06-07T10:12:00'),
  checkOutAt: null,
  checkInStatus: CheckInStatus.ON_TIME,
  checkOutStatus: null,
  status: DayStatus.PRESENT,
  workedMinutes: null,
  isManual: false,
  note: null,
};

export const mockAttendanceHistory: Attendance[] = [
  mockTodayAttendance,
  {
    id: 'att-002',
    companyId: 'company-001',
    userId: 'user-worker-001',
    date: new Date('2026-06-06'),
    checkInAt: new Date('2026-06-06T10:33:00'),
    checkOutAt: new Date('2026-06-06T18:02:00'),
    checkInStatus: CheckInStatus.LATE,
    checkOutStatus: CheckOutStatus.ON_TIME,
    status: DayStatus.LATE,
    workedMinutes: 449,
    isManual: false,
    note: null,
  },
  {
    id: 'att-003',
    companyId: 'company-001',
    userId: 'user-worker-001',
    date: new Date('2026-06-05'),
    checkInAt: new Date('2026-06-05T10:15:00'),
    checkOutAt: new Date('2026-06-05T18:00:00'),
    checkInStatus: CheckInStatus.ON_TIME,
    checkOutStatus: CheckOutStatus.ON_TIME,
    status: DayStatus.PRESENT,
    workedMinutes: 465,
    isManual: false,
    note: null,
  },
  {
    id: 'att-004',
    companyId: 'company-001',
    userId: 'user-worker-001',
    date: new Date('2026-06-04'),
    checkInAt: null,
    checkOutAt: null,
    checkInStatus: null,
    checkOutStatus: null,
    status: DayStatus.ABSENT,
    workedMinutes: 0,
    isManual: false,
    note: null,
  },
  {
    id: 'att-005',
    companyId: 'company-001',
    userId: 'user-worker-001',
    date: new Date('2026-06-03'),
    checkInAt: new Date('2026-06-03T10:10:00'),
    checkOutAt: new Date('2026-06-03T20:20:00'),
    checkInStatus: CheckInStatus.ON_TIME,
    checkOutStatus: CheckOutStatus.OVERTIME,
    status: DayStatus.OVERTIME,
    workedMinutes: 610,
    isManual: false,
    note: null,
  },
  {
    id: 'att-006',
    companyId: 'company-001',
    userId: 'user-worker-001',
    date: new Date('2026-06-02'),
    checkInAt: new Date('2026-06-02T10:15:00'),
    checkOutAt: new Date('2026-06-02T14:00:00'),
    checkInStatus: CheckInStatus.ON_TIME,
    checkOutStatus: CheckOutStatus.LEFT_EARLY,
    status: DayStatus.INCOMPLETE,
    workedMinutes: 225,
    isManual: false,
    note: null,
  },
  {
    id: 'att-007',
    companyId: 'company-001',
    userId: 'user-worker-001',
    date: new Date('2026-06-01'),
    checkInAt: null,
    checkOutAt: null,
    checkInStatus: null,
    checkOutStatus: null,
    status: DayStatus.APPROVED_ABSENCE,
    workedMinutes: 0,
    isManual: false,
    note: 'Отгул (одобрен администратором)',
  },
];

export type OfficeEntry = {
  user: { id: string; fullName: string; avatarUrl: string | null };
  checkInAt: Date;
};

export const mockTodayInOffice: OfficeEntry[] = [
  { user: { id: 'user-worker-001', fullName: 'Иван Петров',       avatarUrl: null }, checkInAt: new Date('2026-06-07T10:12:00') },
  { user: { id: 'user-worker-002', fullName: 'Алексей Козлов',    avatarUrl: null }, checkInAt: new Date('2026-06-07T09:55:00') },
  { user: { id: 'user-worker-004', fullName: 'Константин Дмитриев', avatarUrl: null }, checkInAt: new Date('2026-06-07T09:30:00') },
  { user: { id: 'user-worker-005', fullName: 'Светлана Кузнецова',  avatarUrl: null }, checkInAt: new Date('2026-06-07T10:05:00') },
];
