export const queryKeys = {
  me: ["me"] as const,
  employees: (params?: unknown) => ["employees", params] as const,
  employee: (id: string) => ["employee", id] as const,
  attendance: (params?: unknown) => ["attendance", params] as const,
  inOffice: ["attendance", "in-office"] as const,
  schedules: (params?: unknown) => ["schedules", params] as const,
  requests: (params?: unknown) => ["requests", params] as const,
  news: ["news"] as const,
  officeNetworks: ["office-networks"] as const,
  qr: ["qr"] as const,
  reports: (params?: unknown) => ["reports", params] as const,
  subscription: ["subscription"] as const,
  payments: (params?: unknown) => ["payments", params] as const,
  auditLogs: (params?: unknown) => ["audit-logs", params] as const,
  companies: (params?: unknown) => ["companies", params] as const,
  company: (id: string) => ["company", id] as const,
  providerDashboard: ["provider-dashboard"] as const,
  providerCompanies: (params?: unknown) => ["provider-companies", params] as const,
  providerCompany: (id: string) => ["provider-company", id] as const,
  providerPayments: (params?: unknown) => ["provider-payments", params] as const,
  insight: ["insight"] as const,
  assistantSuggestions: ["assistant", "suggestions"] as const,
};
